### ISSUE TITLE
Multi-tenant - configuration

### ISSUE THREAD

**Issue by bdonchenko** [SAP/ownid-webapp#103]
- Create Aurora DB with customers table
- The table to include all the parameters (now columns) we set in the configuration file
- New parameter (column in the table) per customer - OwnID generated APIKey per customer

Sow:
Discuss with Dor
1. Create DB in AWS
1. Create Table in DB
1. Research standard approaches of client authentication like JWT.... Token identication

**Comment by giladvidal** [comment]
Multi-tenant documents are here:
https://sap.sharepoint.com/:f:/r/teams/OwnID/Shared%20Documents/07%20-%20R%26D/Multi-Tenant?csf=1&web=1&e=1SyPht

**Comment by vitalii-marynkevych** [comment]
create ownid-document-db cluster
it's only available for other applications subnets
no need to create a collection, it will be created automatically
