### ISSUE TITLE
Replace 'You're logged in' message when not logged in

### ISSUE THREAD

**Issue by bdonchenko** [SAP/ownid-webapp#111]
In the scenario where a user click ‘Skip the password’ when they don’t have an account, we create credentials and show “You’re logged in” page. This is when the user is not logged in. Just after this page the user look at the login page and see a message that they should register first or if email identified then to ‘enter password for the last time’.

From Dor:
When the flow needs to continue when we create keys, what do you think about “Device connected” title and then a subtitle with an action like “please continue on desktop” or “click here to continue on nestle.com” if it’s mobile?
When we use existing keys (login), what do you think about “Logged in with your device”?

SoW:

1. Put this screen for all flows when we create Keys.
2. Notice the following page is changed - the frame is blue and the text is updated.

**Comment by giladvidal** [comment]
From Mike:
Mobile Text
Device Connected
Return to Website.com to confirm your account.

Desktop Text
Device Connected
Continue on desktop to Website.com and confirm your account.

Mobile Designs
https://www.figma.com/file/dlZX0QHeDNFD1PQQNWmqNA/FIDO2-Inline-skip-the-password?node-id=1058%3A229

Desktop Designs
https://www.figma.com/file/dlZX0QHeDNFD1PQQNWmqNA/FIDO2-Inline-skip-the-password?node-id=1058%3A1015

**Comment by akayomov** [comment]
Still show's "you are logged in" on link-on-login without FIDO
