### ISSUE TITLE
Update Design: In Reset Password flow the WebApp title should align instead of Registration

### ISSUE THREAD

**Issue by bdonchenko** [SAP/ownid-webapp#113]
Currently, in the flow of 'Reset Password' the text in the WebApp refer 'Registration'. Should be updated to reflect the 'Reset login' or other text that you think is better.

Second, the confirmation page says 'Skip the password enabled!' with a close button. Here also to have a text related to the same context.

**Comment by giladvidal** [comment]
From Mike:

New text
Reset your login
Website.com will recognize your phone the next time you login.

For Desktop:
Your account successfully reset
Continue on desktop to Website.com.
[Close]

For Mobile:
Your account successfully reset
Continue to Website.com.
[Continue]Rese

Designs
iOS - https://www.figma.com/file/qlwlHQT5F5Y3ZIc7hKsmft/OwnID-Demo?node-id=1220%3A60 
Android - https://www.figma.com/file/qlwlHQT5F5Y3ZIc7hKsmft/OwnID-Demo?node-id=213%3A1947

Prototype
https://www.figma.com/proto/qlwlHQT5F5Y3ZIc7hKsmft/OwnID-Demo?node-id=213%3A1152&viewport=2191%2C-333%2C0.1658884733915329&scaling=min-zoom

**Comment by mike-cast** [comment]
### Updated links

Mobile - https://www.figma.com/file/dlZX0QHeDNFD1PQQNWmqNA/Skip-the-password?node-id=1827%3A3454
Desktop - https://www.figma.com/file/dlZX0QHeDNFD1PQQNWmqNA/Skip-the-password?node-id=1827%3A194

**Prototypes**
Mobile - https://www.figma.com/proto/dlZX0QHeDNFD1PQQNWmqNA/Skip-the-password?node-id=1827%3A3454&viewport=776%2C-1095%2C0.1788429170846939&scaling=min-zoom

Desktop - https://www.figma.com/proto/dlZX0QHeDNFD1PQQNWmqNA/Skip-the-password?node-id=1827%3A503&viewport=713%2C139%2C0.11371607333421707&scaling=min-zoom

**Comment by akayomov** [comment]
Pin screen mismatches
![image.png](https://images.zenhubusercontent.com/5fd6737046b97edfd6d4a506/198eac8e-ce20-4a61-83e7-36ab6e7b0e0b)
