### ISSUE TITLE
Add cancel button to disclaimer

### ISSUE THREAD

**Issue by bdonchenko** [SAP/ownid-webapp#116]
Currently the disclaimer has a continue button. After clicking the user back to the page where can click continue or back if would like to cancel. 

Having the ok/cancel in the disclaimer can skip the page and have a better user experience.

Cancel button should be blue.

**Comment by giladvidal** [comment]
From Mike:
Designs: https://www.figma.com/file/dlZX0QHeDNFD1PQQNWmqNA/FIDO2-Inline-skip-the-password?node-id=1354%3A93

Prototype: https://www.figma.com/proto/dlZX0QHeDNFD1PQQNWmqNA/FIDO2-Inline-skip-the-password?node-id=1354%3A93&viewport=875%2C-556%2C0.6586781740188599&scaling=min-zoom
