### ISSUE TITLE
Account recovery fails for phone with FIDO

### ISSUE THREAD

**Issue by akayomov** [SAP/ownid-webapp#160]
**Steps to reproduce:**
1. Go to login page
2. Click "Can't login" button
3. Fill your email
4. Click "Continue"
5. Click link from email
6. Click "Skip the password" 
7. Approve PIN verification
8. Proceed passwordless page with your faceID
9. Observe webapp
**Actual result:** "Connection Lost" error appears in webapp
**Expected:** Recovery should finish successfully

**Comment by akayomov** [comment]
Recovery successfully works if phone has no FIDO configured

**Comment by vitalii-marynkevych** [comment]
please also check Link with fido2, because it was affected by recent changes
