### ISSUE TITLE
iPhone 5s

### ISSUE THREAD

**Issue by giladvidal** [SAP/ownid-webapp#168]
Passcode pages, one last step page don't look good.
Email from Bohdan 22/1.

**Comment by mike-cast** [comment]
**iPhone 5 Passcode**
https://www.figma.com/file/dlZX0QHeDNFD1PQQNWmqNA/Skip-the-password?node-id=1861%3A222

![Screen Shot 2021-01-25 at 11.51.07 AM.png](https://images.zenhubusercontent.com/5ff6187d83f4aa0d523061e4/d3b632fc-fc52-41c7-94fc-d20d15aa7b5c)

**iPhone 8 Passcode**
https://www.figma.com/file/dlZX0QHeDNFD1PQQNWmqNA/Skip-the-password?node-id=1612%3A512
![Screen Shot 2021-01-25 at 11.51.11 AM.png](https://images.zenhubusercontent.com/5ff6187d83f4aa0d523061e4/6be833ae-4b00-4ca1-9f54-23d864d967ed)

**iPhone 5 Account Link**
https://www.figma.com/file/dlZX0QHeDNFD1PQQNWmqNA/Skip-the-password?node-id=1864%3A0
![Screen Shot 2021-01-25 at 11.49.11 AM.png](https://images.zenhubusercontent.com/5ff6187d83f4aa0d523061e4/c1971ca1-fdd2-4ec8-8b0d-5b70bd7dbc87)

**Comment by bdonchenko** [comment]
we can implement it without lock icon for small screens

**Comment by akayomov** [comment]
tested in saucelabs 5s simulator. looks good
