### ISSUE TITLE
Unable to open login page after used magic link

### ISSUE THREAD

**Issue by akayomov** [SAP/ownid-webapp#185]
**Steps to reproduce**
1. Generate magic link
2. Open link from mailbox
3. Observe user is logged in sucessfully
4. Click "Logout" button
5. Try to open /login page
**Actual result:** user is being redirected to main page
**Expected:** user should be able to open login page

**Comment by Tony-Pa** [comment]
Done in context of the #65

**Comment by akayomov** [comment]
Still reproduces. ownid.version: "1.1.43"

**Comment by akayomov** [comment]
FYI requires clean cache for demo site.
