### ISSUE TITLE
BE: Console: delete account

### ISSUE THREAD

**Issue by giladvidal** [SAP/ownid-webapp#199]
Offer a user to delete the account.

- Click to delete
- Ask to approve. Notify that all available apps are going to be deleted along with the account
- Notify that account deleted followed by logout

SoW:

BE

1. Add gigya configuration per environment
1. Integrate with Gigya SDK
1. Create API endpoint to delete account

FE

1. UI
1. Call to BE

**Comment by mike-cast** [comment]
Design
https://www.figma.com/file/85Dd5CEorXrBF7hyBMx6HW/OwnID-Admin-Console?node-id=1016%3A31829

Screen
![Screen Shot 2021-03-19 at 11.23.48 PM.png](https://images.zenhubusercontent.com/5ff6187d83f4aa0d523061e4/b01b1f38-a1a1-4c37-af86-b09354565bf4)
