### ISSUE TITLE
link account - using magic link

### ISSUE THREAD

**Issue by giladvidal** [SAP/ownid-webapp#209]
currently we ask for password in order to complete the link account.

the enhancement is to link the account using magic link - when credentials are created and user found in the identity management system, we can send email to verify the user (like we do in the 'can't login' flow).

**Comment by mike-cast** [comment]
**Designs**
Mobile + Desktop: https://www.figma.com/file/HMLGebZRMAeaGp62lK2zRs/Login?node-id=186%3A5

**Screens**
![Screen Shot 2021-03-20 at 1.02.19 AM.png](https://images.zenhubusercontent.com/5ff6187d83f4aa0d523061e4/a35f504b-5526-495f-89bf-0cd8c92eeb3b)
![Screen Shot 2021-03-20 at 1.02.47 AM.png](https://images.zenhubusercontent.com/5ff6187d83f4aa0d523061e4/06361c51-035b-418a-9ac1-a935892d5777)
