### ISSUE TITLE
Native app - research

### ISSUE THREAD

**Issue by giladvidal** [SAP/ownid-webapp#210]
Currently the flow in the Web is:
- click skip the password
- start OwnID flow using the webapp
- OwnID data is stored in IndexedDB and cookies
- UI sdk polling the server to get login cookies

Native SDK:
- should have same experience to the user
- login from web or native app must rely on same storage so user maintain one credentials for the customer website

The task is to offer a solution (or more than one).

**Comment by dkrivoruchko** [comment]
Native app can launch mobile web browser and get back a notification (in general - some form of callback) when user in Own ID webapp completes flow.
On Android there are two most common ways to do so (without using any external services like pushes) - Deep linking and Android App Links (https://developer.android.com/training/app-links)
Deep links use custom uri schema (like com.ownid.demo://host).
App links use http/https scheme with verification mechanism.

Deep link does not require any user interaction to work, but it is less secure as any app can claim to handle any deep link.
App link is more secure as Android checks if app is allowed to handle specific http(s) link, but it requires user interaction on first use (optionally every time) to allow such redirection.

Both ways allow native app to use current data stored in web browser (seamless integration) in easiest way, but at the same time both are considered public and insecure, and do not recommend being used to send any sensitive data.

Another alternative is to use Chrome Custom tabs (https://developer.chrome.com/docs/android/custom-tabs/overview/) but it requires match more research.
