### ISSUE TITLE
Android: Custom Tabs research

### ISSUE THREAD

**Issue by bdonchenko** [SAP/ownid-webapp#214]
Research technical and functional possibilities to use Custom tabs in OwnID SDK.

Possible cases:

1. Native app handler present -> Open in it
1. else, No web browser in system -> Show error
1. else, One web browser in system
   1. It supports Custom Tab -> Open as Custom Tab
   1. else -> Open as external web browser
1. else, Multiple web browsers in system
   1. Default web browser set
      1. It supports Custom Tab -> Open as Custom Tab
      1. else -> Open as external web browser
   1. else, Show web browser select dialog -> Open as external web browser 

[OwnID-Android-SDK-scope](https://github.tools.sap/OwnID/android-sdk/wiki/OwnID-Android-SDK-scope-(Draft))

**Comment by dkrivoruchko** [comment]
Research technical and functional possibilities to use Custom tabs in OwnID SDK
