### ISSUE TITLE
Link on login feature allows to link multiple devices to same account

### ISSUE THREAD

**Issue by bdonchenko** [SAP/ownid-webapp#92]
**Steps to reproduce:**
1. Create regular not ownID account
2. Log out from it
3. Go to login page
4. Scan QR code with clean phone1
5. Confirm account credentials (account get's linked)
6. Log out from it
7. Go to login page
8. Scan QR code with clean phone2
9. Confirm account credentials
10. Log out from it
11. Observe further behaviour

**Actual result:** System links both devices and allows to enter the account
**Expected result:** As per restriction there should be only one linkage allowed.
WebApp should display an error on second attempt

Desktop env:
1. create a non-OwnID account
2. in login click 'Skip the password'
3. enter password for the last time
4. you are logged-in

5. login again with a second device  scanning the QR
6. enter password for the last time
7. you are logged-in

The second device should fail.

Using Walldorf VPN:
https://accstorefront.cv4c9dq9b-daimaniag1-s1-public.model-t.cc.commerce.ondemand.com/global/en

Looks similar to:
https://app.zenhub.com/workspaces/ownid-5fd226226f88b00011022028/issues/sap/ownid-webapp/92

We should not offer to enter password for the last time and instead display:
There’s another phone associated with this account. If you wish to use this phone, reset your account in the login page.

SoW:

1. Configure demo.ownid.com (dev,staging,prod) to link/register users through the server
1. Test if it works properly

**Comment by giladvidal** [comment]
From Mike:
Designs:
https://www.figma.com/file/dlZX0QHeDNFD1PQQNWmqNA/FIDO2-Inline-skip-the-password?node-id=1038%3A0

Copy:
Unable to verify
There’s another phone associated with this account on Site.com. If you wish to use this phone, reset your account in the login page.

**Comment by giladvidal** [comment]
Dup with ticket 43.

**Comment by akayomov** [comment]
Issue still exists. Tested on phones with FIDO

**Comment by akayomov** [comment]
now it says "invalid loginID or password" on desktop on second linkage. considering this behavior as expected

**Comment by giladvidal** [comment]
I see this which is not the text in the comment above from Mike.

![image.png](https://images.zenhubusercontent.com/5fd2339be5d8bc1d8b14aa91/ad680f7e-aa2c-4639-8461-54f6d8f163ab)

**Comment by giladvidal** [comment]
This is what I see:
![image.png](https://images.zenhubusercontent.com/5fd2339be5d8bc1d8b14aa91/b042f79c-6310-455b-b029-8b41a7f862f9)

When should be:
There’s another phone associated with this account on Site.com. If you wish to use this phone, reset your account in the login page.

**Comment by vitalii-marynkevych** [comment]
There’s another phone associated with this account. If you wish to use this phone, reset your account in the login page.

**Comment by akayomov** [comment]
the same as in last Vitalii's message...

**Comment by vitalii-marynkevych** [comment]
yeah, I changed it. i want to clarify that we don't need to put site.com here
